### ISSUE TITLE
Bug Bash: Tool logs errors downloading NuGet packages but succeeds

### ISSUE THREAD

**Issue by ladipro** [bozturkMSFT/insertions-client#23]
Command line:

```
C:\src\_test\insertions\VS Repo>C:\src\insertions-client\src\InsertionsClient\bin\Debug\netcoreapp3.1\InsertionsClient.exe -d:"C:\src\_test\insertions\VS Repo\.corext\Configs\default.config" -m:"..\Aux Files\sample_manifest.json"
```

Log output:

```
21-4-2020 12:38:47.672526|thread:1|The directory to search for .props files: C:\src\_test\insertions\VS Repo\src\SetupPackages
21-4-2020 12:38:49.648488|thread:13|There is an issue downloading nuget package: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/devdiv/_packaging/VS-CoreXtFeeds/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at Microsoft.Net.Insertions.Api.PropsVariableDeducer.GetPackageFileList(DefaultConfigUpdater defaultConfigUpdater, PackageUpdateResult packageUpdate) in C:\src\insertions-client\src\InsertionsClient\Api\Props\PropsVariableDeducer.cs:line 122

...

Completed successfully.
```

Running the tool again with the same command line but without undoing the changes it's made to config files does not log the errors anymore.

1. Why doesn't the NuGet failure cause the tool to fail?
2. Why does it behave differently depending on the state of the config files?

**Comment by bozturkMSFT** [comment]
1. Props file editing feature is optional. So the tool doesn't consider errors in that step as a failure. 
One of the things we can fix here is: if user doesn't want to use props file editing feature, nuget package downloads shouldn't be attempted. We can't do this now though, because the tool doesn't really know if user wants to enable the feature or not. Adding a new switch "-updatePropsFiles" could solve this. Any thoughts on this?
2. VS repo has lots of nuget packages. We only download nuget packages that was updated.
If you re-run the tool, no packages will be updated on the second run. Therefore, no nuget packages will be downloaded.

**Comment by ladipro** [comment]
> We can't do this now though, because the tool doesn't really know if user wants to enable the feature or not.

If this means that given identical inputs the tool may produce different results depending on whether it has access to the NuGet store or not, then I'd say this is problematic.

> Adding a new switch "-updatePropsFiles" could solve this. Any thoughts on this?

Looks like a good idea. If "-updatePropsFiles" was specified and a NuGet operation failed then the tool would fail as a whole.

> We only download nuget packages that was updated.
If you re-run the tool, no packages will be updated on the second run. Therefore, no nuget packages will be downloaded.

In this case the packages failed to download though. Understood that not updating packages on each run is desirable but here it looks like the tool gave up on that after it didn't work the first time.

- User runs the tool, has networking problems, the tool fails.
- User fixes their network, re-runs the tool.
- Tool does not produce the same results as if it worked on first attempt.

Would this be fixed by introducing "-updatePropsFiles" and not making any changes to the repo if the option is specified and packages fail to update? Thank you!

**Comment by bozturkMSFT** [comment]
Good point.
We can postpone flushing changes to the disk, until we know that all the steps completed successfully.
We still can't guarantee the integrity of the changes, as one of the file save operations may fail. But it should be much rare.

**Comment by ladipro** [comment]
Either this, or maybe being smarter about how the "incremental" run works. I guess the word to use here is "idempotent". Same inputs produce same outputs, even when run repeatedly or with outputs half-modified by a previous failed run.
